const MAX_SHORT_DURATION = 40; 
const NUMBER_CARDS_SCREEN_1280 = 12;
const NUMBER_CARDS_SCREEN_768 = 8;
const NUMBER_CARDS_SCREEN_320 = 5;
const PAGINATION_CARDS = 3;

export {
NUMBER_CARDS_SCREEN_1280,
NUMBER_CARDS_SCREEN_768,
NUMBER_CARDS_SCREEN_320,
PAGINATION_CARDS
}

export default MAX_SHORT_DURATION;